// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH1LZEFzJtW_fGGoBXJBN3iqe59E-jew4',
    appId: '1:449018803871:ios:befc35687371db8847d4aa',
    messagingSenderId: '449018803871',
    projectId: 'fir-in-depth-813e4',
    storageBucket: 'fir-in-depth-813e4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseInDepth',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6-QpvKENj5eqM2rUSip57LrC_19eks0c',
    appId: '1:449018803871:web:33cb40203c4ce86e47d4aa',
    messagingSenderId: '449018803871',
    projectId: 'fir-in-depth-813e4',
    authDomain: 'fir-in-depth-813e4.firebaseapp.com',
    storageBucket: 'fir-in-depth-813e4.firebasestorage.app',
    measurementId: 'G-QZZMP0BPG0',
  );
}
